name: Trigger Netlify Build
on:
  schedule:
    # Run at 0800 UTC daily (9am BST)
    - cron: '30 8 */3 * *'
jobs:
  build:
    name: Run via Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f861746c259078d6f8b8731
